version: "3.7"
services:
  postgres:
    image: postgres:10.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-dbuser}
      POSTGRES_DB: ${POSTGRES_DB:-webshop}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5434:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./db/webshop.sql:/docker-entrypoint-initdb.d/webshop.sql

  # node:
  #   image: ubuntu
  #   platform: linux/arm64
  #   restart: always
  #   working_dir: /app
  #   logging:
  #     options:
  #       max-size: 10m
  #       max-file: "3"
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - .:/app
  #     - ./routes/:/app/routes
  #     - ./controller/:/app/controller
  #   entrypoint: ["/bin/bash", "-c"]
  #   command:
  #     - apt-get update && apt-get install -y nodejs
  #     - apt-get update && apt-get install -y python3
  #     - npm install --silent
  #     - node server.js
